# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. Please do not edit it directly.
class DeltaCli < Formula
  desc "Offline AI Assistant powered by llama.cpp"
  homepage "https://github.com/nile-agi/delta"
  url "https://github.com/nile-agi/delta/archive/refs/tags/v1.0.0.tar.gz"
  sha256 "PLACEHOLDER_SHA256"
  license "MIT"
  head "https://github.com/nile-agi/delta.git", branch: "main", submodules: true

  depends_on "cmake" => :build
  depends_on "curl" => :build
  depends_on "pkg-config" => :build
  depends_on "node" => :build

  on_macos do
    depends_on :macos
  end

  on_linux do
    depends_on "gcc" => :build
  end

  def install
    # Ensure submodules are initialized and updated
    system "git", "submodule", "update", "--init", "--recursive"
    
    # Use already built web UI from public/ if available, otherwise build from assets/
    webui_built = Dir.exist?("public") && (File.exist?("public/index.html") || File.exist?("public/index.html.gz"))
    
    if !webui_built && Dir.exist?("assets")
      ohai "Web UI not found in public/, building from assets/..."
      cd "assets" do
        # Check if node_modules exists, if not install dependencies
        unless Dir.exist?("node_modules")
          system "npm", "install"
        end
        # Build the web UI (outputs to ../public)
        system "npm", "run", "build"
      end
      ohai "Web UI built successfully"
    elsif webui_built
      ohai "Using already built web UI from public/"
    end
    
    # Create build directory
    mkdir "build" do
      system "cmake", "..",
                    "-DCMAKE_BUILD_TYPE=Release",
                    "-DGGML_METAL=#{OS.mac? ? "ON" : "OFF"}",
                    "-DLLAMA_CUDA=OFF",
                    "-DLLAMA_VULKAN=OFF",
                    "-DLLAMA_HIPBLAS=OFF",
                    "-DBUILD_SERVER=ON",
                    "-DUSE_CURL=ON",
                    *std_cmake_args
      system "make", "-j#{ENV.make_jobs}"
    end

    # Install binaries
    bin.install "build/delta"
    bin.install "build/delta-server"

    # Install web UI from public/ directory (built from assets/)
    if Dir.exist?("public") && (File.exist?("public/index.html") || File.exist?("public/index.html.gz"))
      share.install "public" => "delta-cli/webui"
      ohai "Web UI installed from public/"
    else
      opoo "Web UI not found in public/. Server will use embedded UI or find files at runtime."
    end
  end

  test do
    system "#{bin}/delta", "--version"
  end
end

