# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. Please do not edit it directly.
class DeltaCli < Formula
  desc "Offline AI Assistant powered by llama.cpp"
  homepage "https://github.com/nile-agi/delta"
  license "MIT"
  
  # Stable release - installs pre-built binaries (no build tools required)
  # Update version and sha256 when creating a new release
  # url "https://github.com/nile-agi/delta/releases/download/v1.0.0/delta-cli-macos-#{Hardware::CPU.arch}.tar.gz"
  # version "1.0.0"
  # sha256 "PLACEHOLDER_SHA256"
  
  # HEAD version - builds from source (requires Xcode Command Line Tools)
  head "https://github.com/nile-agi/delta.git", branch: "main", submodules: false

  # Build dependencies - only needed for HEAD builds
  depends_on "cmake" => :build
  depends_on "curl" => :build
  depends_on "pkg-config" => :build
  depends_on "node" => :build

  on_macos do
    depends_on :macos
  end

  on_linux do
    depends_on "gcc" => :build
  end

  def install
    # Check if installing from HEAD (source) or stable release (pre-built)
    if build.head?
      install_from_source
    else
      install_from_binary
    end
  end

  def install_from_source
    ohai "Building Delta CLI from source..."
    ohai "This requires Xcode Command Line Tools. If you see build errors, install them with: xcode-select --install"
    
    # Initialize and update only the llama.cpp submodule
    system "git", "submodule", "update", "--init", "vendor/llama.cpp"
    
    # Update llama.cpp's submodules if it has any, but skip problematic nested repos
    if Dir.exist?("vendor/llama.cpp/.gitmodules")
      cd "vendor/llama.cpp" do
        # Remove any nested .git directories that might cause issues (like ios-cmake)
        system "bash", "-c", "find . -name '.git' -type d ! -path './.git/*' -exec rm -rf {} + 2>/dev/null || true"
        # Update submodules, but don't fail if some are missing
        system "git", "submodule", "update", "--init", "--recursive" rescue nil
      end
    end
    
    # Build web UI from assets/ directory before building C++ code
    if Dir.exist?("assets")
      ohai "Building web UI from assets/..."
      cd "assets" do
        # Check if node_modules exists, if not install dependencies
        unless Dir.exist?("node_modules")
          system "npm", "install"
        end
        # Build the web UI (outputs to ../public)
        system "npm", "run", "build"
      end
      cd ".."
    end
    
    # Create build directory and build
    mkdir "build" do
      system "cmake", "..",
                    "-DCMAKE_BUILD_TYPE=Release",
                    "-DGGML_METAL=#{OS.mac? ? "ON" : "OFF"}",
                    "-DLLAMA_CUDA=OFF",
                    "-DLLAMA_VULKAN=OFF",
                    "-DLLAMA_HIPBLAS=OFF",
                    "-DBUILD_SERVER=ON",
                    "-DUSE_CURL=ON",
                    *std_cmake_args
      system "make", "-j#{ENV.make_jobs}"
    end

    # Install binaries
    bin.install "build/delta"
    bin.install "build/delta-server"
    # Install llama.cpp HTTP server so delta-server wrapper can run it (avoids recursion)
    server_path = nil
    %w[build/bin/server build/server build/examples/server build/vendor/llama.cpp/bin/server].each do |p|
      if File.exist?(p)
        server_path = p
        break
      end
    end
    if server_path
      bin.install server_path => "server"
      ohai "Installed llama.cpp server as 'server'"
    else
      opoo "llama.cpp server binary not found; run 'ls build/bin build 2>/dev/null' after build to locate it"
    end

    # Install web UI from public/ directory (built from assets/)
    if Dir.exist?("public") && (File.exist?("public/index.html") || File.exist?("public/index.html.gz"))
      begin
        share.install "public" => "delta-cli/webui"
        ohai "Web UI installed from public/"
      rescue => e
        opoo "Could not install web UI: #{e.message}"
        opoo "The server will work without it or find the source files at runtime."
      end
    else
      ohai "Web UI not found in public/, skipping installation."
      ohai "The server will work without it or find the source files at runtime."
    end
  end

  def install_from_binary
    ohai "Installing pre-built Delta CLI binaries..."
    
    # Determine architecture
    arch = Hardware::CPU.arch.to_s
    platform = OS.mac? ? "macos" : "linux"
    
    # Download pre-built binary
    # Note: This requires a GitHub release with the appropriate binary
    binary_url = "https://github.com/nile-agi/delta/releases/download/v#{version}/delta-cli-#{platform}-#{arch}.tar.gz"
    
    ohai "Downloading from #{binary_url}..."
    system "curl", "-L", "-o", "delta-cli.tar.gz", binary_url
    
    ohai "Extracting..."
    system "tar", "-xzf", "delta-cli.tar.gz"
    
    # Find the extracted directory
    extracted_dir = Dir.glob("delta-cli-*").first
    
    if extracted_dir && Dir.exist?(extracted_dir)
      # Install binaries
      bin.install "#{extracted_dir}/delta"
      bin.install "#{extracted_dir}/delta-server"
      
      # Install web UI if present
      if Dir.exist?("#{extracted_dir}/webui")
        share.install "#{extracted_dir}/webui" => "delta-cli/webui"
        ohai "Web UI installed"
      end
      
      ohai "Delta CLI installed successfully!"
    else
      odie "Failed to extract or find binaries in downloaded archive"
    end
  end

  def post_install
    # Ensure Homebrew bin comes first in PATH to avoid conflicts with llvm's delta
    shell = ENV["SHELL"] || "/bin/zsh"
    shell_config = if shell.include?("zsh")
      File.expand_path("~/.zshrc")
    elsif shell.include?("bash")
      File.expand_path("~/.bash_profile")
    else
      nil
    end
    
    if shell_config && File.exist?(shell_config)
      # Check if PATH fix already exists
      path_fix = '# Delta CLI PATH fix - ensure Homebrew bin comes first'
      unless File.read(shell_config).include?(path_fix)
        File.open(shell_config, "a") do |f|
          f.puts "\n#{path_fix}"
          f.puts 'export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$(echo $PATH | tr ":" "\n" | grep -v "^/opt/homebrew/bin$" | grep -v "^/opt/homebrew/sbin$" | tr "\n" ":" | sed "s/:$//")"'
          f.puts 'alias delta="/opt/homebrew/bin/delta"  # Delta CLI alias to override llvm delta'
        end
        ohai "Added PATH configuration to #{shell_config}"
        ohai "Run 'source #{shell_config}' or restart your terminal to use 'delta' command"
      end
    end
    
    ohai "Delta CLI installed successfully!"
    ohai "To use 'delta' command, run: source #{shell_config}" if shell_config
    ohai "Or use full path: /opt/homebrew/bin/delta"
  end

  test do
    system "#{bin}/delta", "--version"
  end
end

